print("Welcome to Website maker 1.1")
a=input('Enter h1 for heading and p for paragraph: ')
b=input('Enter the text: ')
with open('index.html','w') as f:
    f.write('<!DOCTYPE html>')
    f.write('<html lang="en">')
    f.write('<head>')
    f.write('    <meta charset="UTF-8">')
    f.write('    <meta name="viewport" content="width=device-width, initial-scale=1.0">')
    f.write('    <title>Document</title>')
    f.write('</head>')
    f.write('<body>')
    f.write('<'+a+'>'+b+'</'+a+'>')
    f.write('</body>')
    f.write('</html>')
print("Made by Vampire with ❤️")
n=input('Press "Enter" button for exit')